---
title: "plotDistributions"
author: "Craig A. Wendorf"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Chi Square Distribution Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
if(!require(plotDistributions)) {
if(!require(devtools)) install.packages('devtools')
devtools::install_github("cwendorf/plotDistributions")}
library(plotDistributions)
```

## Chi Square Distribution Examples

### Probability Density Function

Get Probability Density Function plots that specify no limits, numeric limits, and probability limits, respectively.
```{r,chisqPDF}
chisq.pdf(params=c(df=10))
chisq.pdf(params=c(df=10),limits=c(10))
chisq.pdf(params=c(df=10),probs=c(.95,1))
```

### Cumulative Distribution Function

Get Cumulative Distribution Function plots that specify no limits, numeric limits, and probability limits, respectively.
```{r,chisqCDF}
chisq.cdf(params=c(df=10))
chisq.cdf(params=c(df=10),limits=c(10))
chisq.cdf(params=c(df=10),probs=c(.95,1))
```
