---
subtitle: "Chi Square Distribution Examples"
output:
  github_document:
    preserve_yaml: FALSE
vignette: >
  %\VignetteIndexEntry{Chi Square Distribution Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
# suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width = 7, fig.height = 5, fig.path = "figures/", echo = TRUE, warning = FALSE, message = FALSE)
devtools::source_gist("8e6e5dc401e3fc1042ef7a030f9d19c7", filename = "revised_toc.R")
```

```{r,include=FALSE}
if (!require(plotDistributions)) {
  if (!require(remotes)) install.packages("remotes")
  remotes::install_github("cwendorf/plotDistributions")
}
library(plotDistributions)
```

## Chi Square Distribution Examples

```{r toc, echo=FALSE}
thisfile <- knitr::current_input()
revised_toc(thisfile, base_level = 3, toc_depth = 4)
```

---

### Probability Density Function

Get Probability Density Function plots that specify no limits, numeric limits, and probability limits, respectively.
```{r,chisqPDF}
chisq.pdf(params = c(df = 10))
chisq.pdf(params = c(df = 10), limits = c(10))
chisq.pdf(params = c(df = 10), probs = c(.95, 1))
```

### Cumulative Distribution Function

Get Cumulative Distribution Function plots that specify no limits, numeric limits, and probability limits, respectively.
```{r,chisqCDF}
chisq.cdf(params = c(df = 10))
chisq.cdf(params = c(df = 10), limits = c(10))
chisq.cdf(params = c(df = 10), probs = c(.95, 1))
```
